version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: configs
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d configs"]
      interval: 3s
      timeout: 3s
      retries: 20

  app:
    build: .
    environment:
      PG_DSN: "dbname=configs user=postgres password=postgres host=db port=5432"
      PORT: "8080"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    command: ["python", "-m", "app.api"]

  migrate:
    image: postgres:16
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGPASSWORD: postgres
    volumes:
      - ./app/migrations:/migrations
    entrypoint: ["bash","-lc","psql -h db -U postgres -d configs -f /migrations/001_init.sql"]

volumes:
  pgdata:
